USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SUPPORT_INTELLIGENCE_WH;
USE DATABASE SUPPORT_INTELLIGENCE;
USE SCHEMA SUPPORT_OPS;

-- Semantic search over enriched ticket text.
CREATE CORTEX SEARCH SERVICE IF NOT EXISTS SUPPORT_TICKET_SEARCH_SERVICE
  ON TICKET_TEXT
  PRIMARY KEY (TICKET_ID)
  ATTRIBUTES TICKET_ID, PREDICTED_CATEGORY, SENTIMENT, SATISFACTION_RATING, CHANNEL, PRODUCT_LINE
  WAREHOUSE = SUPPORT_INTELLIGENCE_WH
  TARGET_LAG = '1 hour'
AS (
  SELECT
    TICKET_ID,
    TICKET_TEXT,
    PREDICTED_CATEGORY,
    SENTIMENT,
    SATISFACTION_RATING,
    CHANNEL,
    PRODUCT_LINE
  FROM SUPPORT_TICKET_INTELLIGENCE
  WHERE TICKET_TEXT IS NOT NULL
);
