USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SUPPORT_INTELLIGENCE_WH;
USE DATABASE SUPPORT_INTELLIGENCE;
USE SCHEMA SUPPORT_OPS;

-- File formats and stages
CREATE FILE FORMAT IF NOT EXISTS SUPPORT_TICKET_CSV_FORMAT
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE FILE FORMAT IF NOT EXISTS TICKET_METADATA_CSV_FORMAT
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE STAGE IF NOT EXISTS RAW_TICKET_STAGE
  FILE_FORMAT = (FORMAT_NAME = 'SUPPORT_TICKET_CSV_FORMAT');

CREATE STAGE IF NOT EXISTS TICKET_METADATA_STAGE
  FILE_FORMAT = (FORMAT_NAME = 'TICKET_METADATA_CSV_FORMAT');

CREATE STAGE IF NOT EXISTS SEMANTIC_MODEL_STAGE;

-- Tables
CREATE TABLE IF NOT EXISTS RAW_SUPPORT_TICKETS (
  TICKET_ID VARCHAR NOT NULL,
  TICKET_TEXT VARCHAR NOT NULL,
  PRIMARY KEY (TICKET_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS TICKET_METADATA (
  TICKET_ID VARCHAR NOT NULL,
  CREATED_AT TIMESTAMP_NTZ NOT NULL,
  RESOLVED_AT TIMESTAMP_NTZ,
  AGENT_ID VARCHAR,
  ISSUE_CATEGORY VARCHAR,
  SATISFACTION_RATING NUMBER(2, 0),
  CHANNEL VARCHAR,
  PRODUCT_LINE VARCHAR,
  PRIMARY KEY (TICKET_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS SUPPORT_TICKET_INTELLIGENCE (
  TICKET_ID VARCHAR NOT NULL,
  TICKET_TEXT VARCHAR NOT NULL,
  PREDICTED_CATEGORY VARCHAR,
  SENTIMENT FLOAT,
  CREATED_AT TIMESTAMP_NTZ,
  RESOLVED_AT TIMESTAMP_NTZ,
  AGENT_ID VARCHAR,
  ISSUE_CATEGORY VARCHAR,
  SATISFACTION_RATING NUMBER(2, 0),
  CHANNEL VARCHAR,
  PRODUCT_LINE VARCHAR,
  PRIMARY KEY (TICKET_ID) NOT ENFORCED
);
