USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SUPPORT_INTELLIGENCE_WH;
USE DATABASE SUPPORT_INTELLIGENCE;
USE SCHEMA SUPPORT_OPS;

-- Load staged CSV files into Snowflake tables.
COPY INTO RAW_SUPPORT_TICKETS (
  TICKET_ID,
  TICKET_TEXT
)
FROM (
  SELECT
    $1::VARCHAR AS TICKET_ID,
    $5::VARCHAR AS TICKET_TEXT
  FROM @RAW_TICKET_STAGE
)
PATTERN = '.*support_tickets_1000.*[.]csv([.]gz)?'
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO TICKET_METADATA (
  TICKET_ID,
  CREATED_AT,
  RESOLVED_AT,
  AGENT_ID,
  ISSUE_CATEGORY,
  SATISFACTION_RATING,
  CHANNEL,
  PRODUCT_LINE
)
FROM (
  SELECT
    $1::VARCHAR AS TICKET_ID,
    TRY_TO_TIMESTAMP_NTZ($2) AS CREATED_AT,
    TRY_TO_TIMESTAMP_NTZ(NULLIF($3, '')) AS RESOLVED_AT,
    $4::VARCHAR AS AGENT_ID,
    $5::VARCHAR AS ISSUE_CATEGORY,
    TRY_TO_NUMBER($7) AS SATISFACTION_RATING,
    $8::VARCHAR AS CHANNEL,
    $9::VARCHAR AS PRODUCT_LINE
  FROM @TICKET_METADATA_STAGE
)
PATTERN = '.*ticket_metadata_200.*[.]csv([.]gz)?'
ON_ERROR = 'ABORT_STATEMENT';

-- Build the table used by Cortex and the Streamlit app.
MERGE INTO SUPPORT_TICKET_INTELLIGENCE AS target
USING (
  SELECT
    raw_tickets.TICKET_ID,
    raw_tickets.TICKET_TEXT,
    metadata.CREATED_AT,
    metadata.RESOLVED_AT,
    metadata.AGENT_ID,
    metadata.ISSUE_CATEGORY,
    metadata.SATISFACTION_RATING,
    metadata.CHANNEL,
    metadata.PRODUCT_LINE
  FROM RAW_SUPPORT_TICKETS AS raw_tickets
  LEFT JOIN TICKET_METADATA AS metadata
    ON raw_tickets.TICKET_ID = metadata.TICKET_ID
) AS source
ON target.TICKET_ID = source.TICKET_ID
WHEN MATCHED THEN UPDATE SET
  target.TICKET_TEXT = source.TICKET_TEXT,
  target.CREATED_AT = source.CREATED_AT,
  target.RESOLVED_AT = source.RESOLVED_AT,
  target.AGENT_ID = source.AGENT_ID,
  target.ISSUE_CATEGORY = source.ISSUE_CATEGORY,
  target.SATISFACTION_RATING = source.SATISFACTION_RATING,
  target.CHANNEL = source.CHANNEL,
  target.PRODUCT_LINE = source.PRODUCT_LINE
WHEN NOT MATCHED THEN INSERT (
  TICKET_ID,
  TICKET_TEXT,
  CREATED_AT,
  RESOLVED_AT,
  AGENT_ID,
  ISSUE_CATEGORY,
  SATISFACTION_RATING,
  CHANNEL,
  PRODUCT_LINE
)
VALUES (
  source.TICKET_ID,
  source.TICKET_TEXT,
  source.CREATED_AT,
  source.RESOLVED_AT,
  source.AGENT_ID,
  source.ISSUE_CATEGORY,
  source.SATISFACTION_RATING,
  source.CHANNEL,
  source.PRODUCT_LINE
);
