USE ROLE ACCOUNTADMIN;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS SUPPORT_INTELLIGENCE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS SUPPORT_INTELLIGENCE;

CREATE SCHEMA IF NOT EXISTS SUPPORT_INTELLIGENCE.SUPPORT_OPS;

USE WAREHOUSE SUPPORT_INTELLIGENCE_WH;
USE DATABASE SUPPORT_INTELLIGENCE;
USE SCHEMA SUPPORT_OPS;
